{{- if .Values.seed_data.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "konga.fullname" . }}-seed-data
  labels:
    app.kubernetes.io/name: {{ include "konga.name" . }}
    helm.sh/chart: {{ include "konga.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- if .Values.seed_data.node_data }}
  node_data_source: |
    module.exports = {{ toJson .Values.seed_data.node_data }}
  {{- end }}
  {{- if .Values.seed_data.user_data }}
  user_data_source: |
    module.exports = {{ toJson .Values.seed_data.user_data }}
  {{- end }}
{{- end }}
