apiVersion: v2
description: Installs Ansible AWX (Ansible Web UI), with dependencies (rabbitmq, postgresql, memcahed)
name: awx
version: 1.5.0
appVersion: 2.2.4
maintainers:
  - name: Qumulus Technology LTD
    email: admin@qumulus.com
sources:
  - https://github.com/ansible/awx
keywords:
- ansible
- awx
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 11.6.3
- name: rabbitmq
  version: 10.1.5
  repository: https://charts.bitnami.com/bitnami
  condition: rabbitmq.enabled
- name: memcached
  version: 6.1.1
  repository: https://charts.bitnami.com/bitnami
  condition: memcached.enabled